//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlProteinasClient.RegistroProteinas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int GoalField;
        
        private int TotalField;
        
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Goal {
            get {
                return this.GoalField;
            }
            set {
                if ((this.GoalField.Equals(value) != true)) {
                    this.GoalField = value;
                    this.RaisePropertyChanged("Goal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegistroProteinas.RegistroProteinasServicesSoap")]
    public interface RegistroProteinasServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProtein", ReplyAction="*")]
        int AddProtein(int amount, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddProtein", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddProteinAsync(int amount, int userId);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        ControlProteinasClient.RegistroProteinas.AddUserResponse AddUser(ControlProteinasClient.RegistroProteinas.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlProteinasClient.RegistroProteinas.AddUserResponse> AddUserAsync(ControlProteinasClient.RegistroProteinas.AddUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listUsersResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listUsers", ReplyAction="*")]
        ControlProteinasClient.RegistroProteinas.listUsersResponse listUsers(ControlProteinasClient.RegistroProteinas.listUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<ControlProteinasClient.RegistroProteinas.listUsersResponse> listUsersAsync(ControlProteinasClient.RegistroProteinas.listUsersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public ControlProteinasClient.RegistroProteinas.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(ControlProteinasClient.RegistroProteinas.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int goal;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string name, int goal) {
            this.name = name;
            this.goal = goal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ControlProteinasClient.RegistroProteinas.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(ControlProteinasClient.RegistroProteinas.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(int AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listUsers", Namespace="http://tempuri.org/", Order=0)]
        public ControlProteinasClient.RegistroProteinas.listUsersRequestBody Body;
        
        public listUsersRequest() {
        }
        
        public listUsersRequest(ControlProteinasClient.RegistroProteinas.listUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listUsersRequestBody {
        
        public listUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ControlProteinasClient.RegistroProteinas.listUsersResponseBody Body;
        
        public listUsersResponse() {
        }
        
        public listUsersResponse(ControlProteinasClient.RegistroProteinas.listUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ControlProteinasClient.RegistroProteinas.User[] listUsersResult;
        
        public listUsersResponseBody() {
        }
        
        public listUsersResponseBody(ControlProteinasClient.RegistroProteinas.User[] listUsersResult) {
            this.listUsersResult = listUsersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistroProteinasServicesSoapChannel : ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroProteinasServicesSoapClient : System.ServiceModel.ClientBase<ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap>, ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap {
        
        public RegistroProteinasServicesSoapClient() {
        }
        
        public RegistroProteinasServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroProteinasServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroProteinasServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroProteinasServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddProtein(int amount, int userId) {
            return base.Channel.AddProtein(amount, userId);
        }
        
        public System.Threading.Tasks.Task<int> AddProteinAsync(int amount, int userId) {
            return base.Channel.AddProteinAsync(amount, userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlProteinasClient.RegistroProteinas.AddUserResponse ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap.AddUser(ControlProteinasClient.RegistroProteinas.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public int AddUser(string name, int goal) {
            ControlProteinasClient.RegistroProteinas.AddUserRequest inValue = new ControlProteinasClient.RegistroProteinas.AddUserRequest();
            inValue.Body = new ControlProteinasClient.RegistroProteinas.AddUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.goal = goal;
            ControlProteinasClient.RegistroProteinas.AddUserResponse retVal = ((ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlProteinasClient.RegistroProteinas.AddUserResponse> ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap.AddUserAsync(ControlProteinasClient.RegistroProteinas.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlProteinasClient.RegistroProteinas.AddUserResponse> AddUserAsync(string name, int goal) {
            ControlProteinasClient.RegistroProteinas.AddUserRequest inValue = new ControlProteinasClient.RegistroProteinas.AddUserRequest();
            inValue.Body = new ControlProteinasClient.RegistroProteinas.AddUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.goal = goal;
            return ((ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlProteinasClient.RegistroProteinas.listUsersResponse ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap.listUsers(ControlProteinasClient.RegistroProteinas.listUsersRequest request) {
            return base.Channel.listUsers(request);
        }
        
        public ControlProteinasClient.RegistroProteinas.User[] listUsers() {
            ControlProteinasClient.RegistroProteinas.listUsersRequest inValue = new ControlProteinasClient.RegistroProteinas.listUsersRequest();
            inValue.Body = new ControlProteinasClient.RegistroProteinas.listUsersRequestBody();
            ControlProteinasClient.RegistroProteinas.listUsersResponse retVal = ((ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap)(this)).listUsers(inValue);
            return retVal.Body.listUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ControlProteinasClient.RegistroProteinas.listUsersResponse> ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap.listUsersAsync(ControlProteinasClient.RegistroProteinas.listUsersRequest request) {
            return base.Channel.listUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ControlProteinasClient.RegistroProteinas.listUsersResponse> listUsersAsync() {
            ControlProteinasClient.RegistroProteinas.listUsersRequest inValue = new ControlProteinasClient.RegistroProteinas.listUsersRequest();
            inValue.Body = new ControlProteinasClient.RegistroProteinas.listUsersRequestBody();
            return ((ControlProteinasClient.RegistroProteinas.RegistroProteinasServicesSoap)(this)).listUsersAsync(inValue);
        }
    }
}
